# Imagen oficial de PostgreSQL
FROM postgres:latest

# Define las variables de entorno para PostgreSQL
ENV POSTGRES_USER=thor
ENV POSTGRES_PASSWORD=th0r*2025
ENV POSTGRES_DB=payments

# Expone el puerto 5433 en lugar del 5432
EXPOSE 5435

# Inicia el servicio de PostgreSQL
CMD ["postgres"]
